
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dentplex.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Slider
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Slider()
    {

        this.SliderItems = new HashSet<SliderItem>();

    }


    public int SlideID { get; set; }

    public string SlideTitle { get; set; }

    public string SlideImage { get; set; }

    public bool SlideIsActive { get; set; }

    public string SlideDesc { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SliderItem> SliderItems { get; set; }

}

}
