
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dentplex.Data.Model
{

using System;
    using System.Collections.Generic;
    
public partial class SliderItem
{

    public int SlideItemID { get; set; }

    public int SlideID { get; set; }

    public string SlideItemTitle { get; set; }

    public string SlideItemImage { get; set; }

    public string SlideItemLink { get; set; }

    public int SlideItemOrder { get; set; }



    public virtual Slider Slider { get; set; }

}

}
